#Jenkins Installation on Master node
- hosts: j-master
  become: yes
  tasks:
    - name: ensure the jenkins apt repository key is installed
      shell: "curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee   /usr/share/keyrings/jenkins-keyring.asc > /dev/null"    
    - name: 
      shell: "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]   https://pkg.jenkins.io/debian binary/ | sudo tee   /etc/apt/sources.list.d/jenkins.list > /dev/null"
    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes
    - name: ensure jenkins is running
      service: name=jenkins state=started
